name: Release Extension

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Create ZIP package
        run: pnpm zip

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: ./chrome-extension/dist/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./chrome-extension/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
